import type { Metadata } from 'next'
import { Nunito_Sans } from 'next/font/google'
import '@/styles/globals.css'

import Providers from '@/app/providers'
import { Toaster } from '@/components/ui/sonner'
import { Header } from '@/components/common/header'
import { Footer } from '@/components/common/footer'
import { cn } from '@/lib/utils'

const nunitoSans = Nunito_Sans({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Bookstore App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" suppressHydrationWarning>
    <body
      className={cn(
        'bg-neutral-200 dark:bg-background font-sans antialiased',
        nunitoSans.className,
      )}
    >
    <Providers>
      <Toaster richColors />
      <Header />
      <main className="relative mx-auto max-w-7xl px-4 md:px-8 pt-8 mb-4">
        {children}
      </main>
      <Footer />
    </Providers>
    </body>
    </html>
  )
}
